package GUI;

import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arias
 */
public class Pantalla extends javax.swing.JFrame {
    private static ArrayList<String> ciudad = new ArrayList<>();
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPantalla = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmAgregarCliente = new javax.swing.JMenuItem();
        jmBuscarCliente = new javax.swing.JMenuItem();
        jmBorrarCliente = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        jmBuscarClientesCiudad = new javax.swing.JMenuItem();
        jmBuscarTelefonoApellido = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmAgregarCiudad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPantallaLayout = new javax.swing.GroupLayout(jdpPantalla);
        jdpPantalla.setLayout(jdpPantallaLayout);
        jdpPantallaLayout.setHorizontalGroup(
            jdpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        jdpPantallaLayout.setVerticalGroup(
            jdpPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        jmAgregarCliente.setText("agregar cliente");
        jmAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmAgregarCliente);

        jmBuscarCliente.setText("buscar cliente");
        jmBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmBuscarCliente);

        jmBorrarCliente.setText("borrar cliente");
        jmBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBorrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmBorrarCliente);

        jMenuBar2.add(jMenu1);

        jmDirectorio.setText("Directorio");

        jmBuscarClientesCiudad.setText("buscar clientes por ciudad");
        jmBuscarClientesCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarClientesCiudadActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmBuscarClientesCiudad);

        jmBuscarTelefonoApellido.setText("buscar telefono por apellido");
        jmBuscarTelefonoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarTelefonoApellidoActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmBuscarTelefonoApellido);

        jMenuBar2.add(jmDirectorio);

        jMenu3.setText("Ciudades");

        jmAgregarCiudad.setText("agregar ciudad");
        jmAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarCiudadActionPerformed(evt);
            }
        });
        jMenu3.add(jmAgregarCiudad);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Salir");

        jmSalir.setText("salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu4.add(jmSalir);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPantalla)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPantalla)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarClienteActionPerformed
        // TODO add your handling code here:
        AgregarCliente agCliente = new AgregarCliente(Pantalla.ciudad);
        jdpPantalla.add(agCliente);
        agCliente.setVisible(true);
    }//GEN-LAST:event_jmAgregarClienteActionPerformed

    private void jmBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBorrarClienteActionPerformed
        // TODO add your handling code here:
        
        BorrarCliente bCliente = new BorrarCliente();
        jdpPantalla.add(bCliente);
        bCliente.setVisible(true);
        
    }//GEN-LAST:event_jmBorrarClienteActionPerformed

    private void jmBuscarClientesCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarClientesCiudadActionPerformed
        // TODO add your handling code here:
        
        BuscarClienteporCiudad bcpCiudad = new BuscarClienteporCiudad();
        jdpPantalla.add(bcpCiudad);
        bcpCiudad.setVisible(true);
        
    }//GEN-LAST:event_jmBuscarClientesCiudadActionPerformed

    private void jmBuscarTelefonoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarTelefonoApellidoActionPerformed
        // TODO add your handling code here:
        
        BuscarTelefonoporApellido btpApellido = new BuscarTelefonoporApellido();
        jdpPantalla.add(btpApellido);
        btpApellido.setVisible(true);
    }//GEN-LAST:event_jmBuscarTelefonoApellidoActionPerformed

    private void jmAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarCiudadActionPerformed
        // TODO add your handling code here:
        AgregarCiudad aCiudad = new AgregarCiudad(Pantalla.ciudad);
        jdpPantalla.add(aCiudad);
        aCiudad.setVisible(true);
    }//GEN-LAST:event_jmAgregarCiudadActionPerformed

    private void jmBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarClienteActionPerformed
        // TODO add your handling code here:
        
        BuscarCliente bCliente = new BuscarCliente();
        jdpPantalla.add(bCliente);
        bCliente.setVisible(true);
        
        
    }//GEN-LAST:event_jmBuscarClienteActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JDesktopPane jdpPantalla;
    private javax.swing.JMenuItem jmAgregarCiudad;
    private javax.swing.JMenuItem jmAgregarCliente;
    private javax.swing.JMenuItem jmBorrarCliente;
    private javax.swing.JMenuItem jmBuscarCliente;
    private javax.swing.JMenuItem jmBuscarClientesCiudad;
    private javax.swing.JMenuItem jmBuscarTelefonoApellido;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
